### ISSUE TITLE
text is not updated

### ISSUE THREAD

**Issue by salmon-charles** [rdkcentral/Lightning#109]
Hello,

I have a problem on an application, where I change the value of a text but the text is not updated (visually).
I can not reproduce the problem yet by using a simple test case, but here are the results of my experimentations.

The following is the trace that happen on the texture that is not updated:

```
TextTexture[13329] - set text Plus belle la vie
TextTexture[13329] - _updateSource (isUsed:true)
...
TextTexture[13329] - becomesUnused
...
TextTexture[13329] - _performUpdateSource (isUsed: false)
...
TextTexture[13329] - becomesUsed
```

The problem is that, when the texture becomes used again, the `_performUpdateSource` has already been called, but the texture has not been updated because, between the `_updateSource` and the `_performUpdateSource`, it has been unused.

By looking the method `_performUpdateSource`, there is the comment that said 
> If, in the meantime, the texture was no longer used, just remember that it must update until it becomes used

But I don't understand how this special case is handled.

```
_performUpdateSource(force = false) {
        // If, in the meantime, the texture was no longer used, just remember that it must update until it becomes used
        // again.
        if (force || this.isUsed()) {
            this._mustUpdate = false;
            let source = this._getTextureSource();
            this._replaceTextureSource(source);
        }
    }
```

According to me, if the texture is not used, we should make sure the `_mustUpdate` flag is set to `true`, so when the texture will become used again, the `load()` method will call the `_performUpdateSource` (by using the `this.source`) ?

On my side, the following works:

```
_performUpdateSource(force = false) {
        if (force || this.isUsed()) {
            this._mustUpdate = false;
            let source = this._getTextureSource();
            this._replaceTextureSource(source);
        } else {
            // If, in the meantime, the texture was no longer used, just remember that it must update until it becomes used again.
            this._mustUpdate = true;
        }
    } 
```

There are other places where we could fix the problem, and I can't really tell you how to reproduce the problem.
I just want to know if this fix looks acceptable for you.

**Comment by g-zachar** [comment]
Hi @salmon-charles,

Thanks for reporting.

Is `_changed()` method called between `becomesUnused()` and `performUpdateSource()`? Because it should've been called if texture source is currently unused and set `_mustUpdate` flag to `true`. How exactly are you changing value of text?

Best regards

**Comment by erikhaandrikman** [comment]
@salmon-charles any updates? Or can we close this ticket?

**Comment by g-zachar** [comment]
Closing for now, please reopen if still relevant.
