### ISSUE TITLE
[FEATURE] Logs STATE "PATH" as same as FOCUS

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [rdkcentral/Lightning#128]

**Comment by erikhaandrikman** [comment]
Is it possible to provide a bit more context?

**Comment by MattiaPontonioKineton** [comment]
When the focus changes the framework logs.
I'm looking for a Way to see even when states are switched and where.
Maybe an optional log inside `_setState` function.

- https://webplatformforembedded.github.io/Lightning/docs/components/statemachine/statemachine
- https://webplatformforembedded.github.io/Lightning/docs/components/statemachine/switchingstates

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

There are no future plans to extend state machine in any way.

Best regards
