### ISSUE TITLE
Inconsistency in VS Code type checking

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#145]
@g-zachar,
thanks for the clarification.
As a side note, I want to suggest that this causes inconsistency in VS Code type checking. It may drives to error the use of the `class` keyword.
It's a sort of downgrades of the JavaScript features.
Anyway, If it drives to better code It should be followed.
![image](https://user-images.githubusercontent.com/44380480/77672012-a902f480-6f88-11ea-83e8-3692510fe7b2.png)
Best regards,
Mattia

_Originally posted by @mattiapontonio in https://github.com/WebPlatformForEmbedded/Lightning/issues/139#issuecomment-604537508_

**Comment by mattiapontonio** [comment]
https://github.com/WebPlatformForEmbedded/Lightning/issues/144

**Comment by g-zachar** [comment]
Not much we can do about it.
