### ISSUE TITLE
Animation finish with wrongs values

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#156]
I've defined this animation (computed in a getter):
```
{
    duration: 0.5,
    repeat: 0,
    stopMethod: 'immediate',
    actions: [{
        p: 'y',
        v: {
            0: this.y,
            0.5: this.y - 50,
            1: this.y
        }
    }]
}
```
I've setup the handler (even this is computed in a getter).
(If it is relevant) Animations are 4 computet in a `get animations(){}`.
```
Object.values(animations).forEach(a => a.on('finish', this.finish));
```
```
get finish() {
    return () => {
        this.fireAncestors('$positionMoved', this.x, this.y, this.playerId);
    };
}
```
The element starts from a position of x = 0, y = 0 (checker in the debugger);
```
$positionMoved(x, y, playerId) {
    const index = playerId || 0;
    const can = this.tag('Markers').check(x, y);
    if (can) this.tag('Cursors').childList.getAt(index).enable();
    if (!can) this.tag('Cursors').childList.getAt(index).disable();
}
```
In this handler I got:
```
x = 0, y = -0.29488556486184336
```
Expected:
```
x = 0, y = 0
```

## Simple definition
I need to animate a cursor on top, left, right, bottom simulate the inability of going forward, then recheck if I have to disable it based on the position of It started. For achieve this, I've stopped common handlers of checking both from transition and animations.

- How can I be sure that the position is correct after the finish of the animation?
- There are other patterns?
- Is some related to animation frames?
- It is some related to the configs of the animations?

# Extra
I need even to disable handlers (ex: _handleEnter()) during animation to prevent bad interactions.

Best regards
Mattia

**Comment by erikhaandrikman** [comment]
Can you provide an example that we can run and debug?

**Comment by mattiapontonio** [comment]
@erikhaandrikman,
This is a similar case to my personal case.
This reproduces and considers only the `finish` event and the `y` coordinate animation.
Assertion fails.
https://jsfiddle.net/e563mtjh/6/
## Code
```
// Open console, focus canvas and press Enter, then see the assertion test
class AnimationsExample extends lng.Application {
  static _template() {
    return {
   		y: 10,
    	text: { text: 'Enter' }
    }
  }
  get object() {
  	return {
      y: this.y
    }
  }
  get handlers() {
  	return {
      finish: ()=> {
      	this.fireAncestors('$finish', this.object);
        console.assert(this.object.y == 10, JSON.stringify(this.object));
      }
    }
  }
  get animations() {
  	const animations = [
      this.animation({
          duration: 0.5,
          repeat: 0,
          stopMethod: 'immediate',
          actions: [{
            p: 'y',
            v: {
              0: this.y,
              0.5: this.y - 50,
              1: this.y
            }
          }]
        })
    ];
    animations[0].on('finish', this.handlers.finish);
    return animations;
  }
  _handleEnter() {
  	this.animations[0].start();
  }
}
const options = {stage: {w: 600, h: 600, clearColor: 0xFF000000, canvas2d: false, useImageWorker: false}, debug: true}
const app = new AnimationsExample(options);
window.app = app;
document.body.appendChild(app.stage.getCanvas());
```
## lightning.js
https://unpkg.com/wpe-lightning@1.7.0/dist/lightning.js
