### ISSUE TITLE
No Text on PS4: WebGLTexture, createImageBitmap, and ImageData not defined

### ISSUE THREAD

**Issue by WillsonHaw** [rdkcentral/Lightning#16]
There were a couple issues we had while trying to run Lightning on a couple of different platforms that are on older browser engines, like LG WebOS 2 and Playstation 4.

`WebGLTexture` and `createImageBitmap` is undefined for PS4. We've had to polyfill `createImageBitmap` using something like:

```
if (!('createImageBitmap' in window)) {
  window.createImageBitmap = async function(blob) {
    return new Promise((resolve, reject) => {
      const img = document.createElement('img');
      img.addEventListener('load', function() {
        resolve(this);
      });
      img.src = window.URL.createObjectURL(blob);
    });
  };
}
```

and we also changed `_isNativeTexture` to something like:

```
_isNativeTexture(source) {
  if (Utils.isNode) {
    return source.constructor.name === "WebGLTexture";
  }

  if ('WebGLTexture' in window) {
    return source instanceof WebGLTexture;
  }

  return false;
}
```

to prevent an exception from occurring.

`ImageData` was also missing, and we've polyfilled it using [this gist](https://gist.github.com/Convicted202/7684bc8113b3011b4a6a1b2aa9f7a36f) that we found.

Note: Web Workers also will not have the polyfills. So the `createImageBitmap` polyfill above will not work! We also lose things like `Map` support for older browsers

**Comment by WillsonHaw** [comment]
Another one that was not polyfilled was `createObjectURL`.

**Comment by WillsonHaw** [comment]
For `createObjectURL`, it looks like it wasn't because of missing `createObjectURL`, but it is actually erroring with a `Type Error` when executing. It seems the mimetype passed to the function is causing the error. This was fixed for me by setting the type on the blob instead:

```
const blob = new Blob([code.replace('"use strict";', '')], { type: 'application/javascript; charset=utf-8' });
const blobURL = (window.URL ? URL : webkitURL).createObjectURL(blob);
```

**Comment by g-zachar** [comment]
I'm closing this issue for now, please reopen if still relevant.

**Comment by markus101** [comment]
I believe the change to `_isNativeTexture` would still be good to have, we can survive without the polyfills though.

**Comment by g-zachar** [comment]
Hey @markus101,

It's possible that webOS 2 was not taken into consideration back when Lightning was tested on variety of platforms in its earlier stages. Currently, we are not pursuing this target, however if you wish to contribute (looks like the solution is already there), we could consider adding the change to mainstream (including polyfills).

Best regards

**Comment by markus101** [comment]
This issue was originally regarding PS4, which didn't have issues rendering text and even with the polyfills above webOS 2 is unable to render text. I'm not sure this issue is related to #100.

**Comment by g-zachar** [comment]
Hi @markus101 ,

I see, since you commented on this issue I thought you've found your answer here. So, if I understood you correctly, the change and polyfills would fix problems on PS4 but webOS 2 is still open, correct?

Best regards

**Comment by markus101** [comment]
Correct, webOS 2 still has issues. I commented here because as far as I can tell the `_isNativeTexture` wasn't implemented and will still affect PS4.

**Comment by g-zachar** [comment]
@markus101 , thanks for clarification. We are not running any tests on PS4 neither, so if you wish to contribute a fix and can confirm it works on PS4 platform, we can include it in upstream. I'll reopen the webOS 2 issue then.

Best regards
