### ISSUE TITLE
Vertically centering text with large lineHeights

### ISSUE THREAD

**Issue by frank-weindel** [rdkcentral/Lightning#164]
I’m trying to use flexbox to vertically center some text that could either be one or two lines with an icon that’s on its left. There isn’t much problem if I use a tight lineHeight, but as soon as I go higher with it, its aligned to the top. Is there any way to have text be centered within the lineHeight lines instead of just aligned to the top?

Example Fiddle: https://jsfiddle.net/foxtrotwhiskey9/fkpou9js/2/

**Comment by mattiapontonio** [comment]
@frank-weindel hello,
please look at this edit that could be improved as well:
https://jsfiddle.net/jLqwdzbg/

**Comment by g-zachar** [comment]
@mattiapontonio 
Thanks for contributing

@frank-weindel 
Please see the example: https://jsfiddle.net/0bozj2wq/2/

Let me know if you have any further questions.

Best regards

**Comment by frank-weindel** [comment]
Thanks @mattiapontonio @g-zachar 

In both of your examples you've reduced my lineHeight. I would like that to remain at 50.

@g-zachar I could replicate exactly what you did there in my original example just by adding a `y` constant (12 in this case) to my Subtitle element. While I can certainly hard code a value there, I'm more looking for a solution that automatically centers whatever text I have in there with whatever lineHeight I might have. Is that possible today? Could something be added by lightning to support this?

**Comment by g-zachar** [comment]
@frank-weindel 

It looks like `lineHeight` implementation is not accurate as the text should be vertically centered in the final texture. Considering this, I don't think currently there is a better way than to hardcode the offset (or perhaps calculate it based on text's `fontSize` and `lineHeight` properties to be more generic)

Best regards

**Comment by frank-weindel** [comment]
@g-zachar @erikhaandrikman Thanks for fixing this!
