### ISSUE TITLE
Random error rendering on testing with Cypress

### ISSUE THREAD

**Issue by jhderojasUVa** [rdkcentral/Lightning#175]
Hi,

We are testing Lightning with Cypress both for unit and for e2e via injecting the components into an html file on the fixtures and letting webpack to take the images of the static directory (where you put the images in), running a webpack dev server and letting do the job for having everything tunning for Cypress and... randomly (it means not always) we receive, from time to time this error on the test:

__Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'__

Sometimes the same tests run smoothly and other throw the same error all the time until we close and open the browser or (if we are running the browser less test) we add a line into the test (that do nothing, or nothing into the test).

It's very bad to reproduce because seems aleatory but seems not (it's likely when you are showing images on the tests).

For more information:

We have create a command in Cypress that create the app by using the class that extend the lightning.application with an empty template and create the stage where the components are in.

Then, we use an index.html file as a fixture and we add the stage to the body of the HTML.

After that we create the component and we add into the stage (and trigger the draw).

**Comment by g-zachar** [comment]
Hi @jhderojasUVa 

I can see that you use very customized environment. Can you share a project with environment that would allow me to try to reproduce it myself?

Best regards

**Comment by jhderojasUVa** [comment]
Hi,

Sorry for the delay. My fault, as always.

Here's an example of the project: https://github.com/jhderojasUVa/lightningtestcypress

That is the environment with one example (sorry for the image of the cats).

As you will see, we use: yarn test:debug

It starts webpack in the way I told you and then starts cypress wher you can choose the test.

As I told you, the error is random. On the time when I uploaded the project was working on a Macintosh machine with latest version of node (in fact doesn't care because all relays on the web browser) but not in a Windows machine with the same version of all.

If you have any questions that I can help, please, let me know.

**Comment by g-zachar** [comment]
Hi @jhderojasUVa 

I'm having trouble trying to run your project. Can you post all the steps and expected outcome, so that I am not missing anything?

Best regards

**Comment by jhderojasUVa** [comment]
Hi,

I will close this issue because it seems that it not happen again thanks to the update of lightning.

Thanks!
