### ISSUE TITLE
getSmooth pourpose

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#179]
What exactly `getSmooth` do instead of simply access the property?
https://webplatformforembedded.github.io/Lightning/docs/transitions/events

**Comment by mattiapontonio** [comment]
![image](https://user-images.githubusercontent.com/44380480/81975308-1e08b700-9627-11ea-99cb-1c534db72d48.png)
It also does not be found by Algolia.

**Comment by victortwc** [comment]
AFAIK, `setSmooth` does not set the property value but instead it changes a `smooth` representation of that property. Looking at the source code you can see it sets the value inside the element's transition reference.

```
getSmooth(property, v) {
        let t = this._getTransition(property);
        if (t && t.isAttached()) {
            return t.targetValue;
        } else {
            return v;
        }
    }
```

**Comment by mattiapontonio** [comment]
`getSmooth` return the final property of a transition? 
Can You documents?
Regards

**Comment by victortwc** [comment]
This is actually documented here: https://rdkcentral.github.io/Lightning/docs/transitions/overview#transition-target-value

**Comment by mattiapontonio** [comment]
Ok. I Will close this. It could be improved giving heading to the method's names.
Regards
