### ISSUE TITLE
Algolia Search in DOC still search in webplatformforembedded.github.io instead of rdkcentral.github.io

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#182]

**Comment by michielvandergeest** [comment]
@Thomvl can you look into this?

**Comment by Thomvl** [comment]
Requested a new key, will fix it once we have it.

**Comment by Thomvl** [comment]
Search should work again!

**Comment by mattiapontonio** [comment]
![image](https://user-images.githubusercontent.com/44380480/82801514-b7cd3100-9e7d-11ea-8860-4bcec84bcafb.png)
