### ISSUE TITLE
404 - https://rdkcentral.github.io/Lightning/docs/gettingStarted/web

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#184]
Broken link in DOC, the Getting Started in bottom.

![image](https://user-images.githubusercontent.com/44380480/82887769-c16f9b00-9f48-11ea-9864-f3b174e39767.png)

**Comment by michielvandergeest** [comment]
Can you look at this one as well @Thomvl? Thx :)
