### ISSUE TITLE
Displaying last characters of a string in text area on overflow

### ISSUE THREAD

**Issue by vnarni** [rdkcentral/Lightning#187]
Hi,
Is there any property/way to display last characters of a string in text area on overflow ? for example "old text should not be displayed **only the newer should**". So I want to make the text in bold to be visible based on the width. 

Thanks,
Venkata Narni

**Comment by g-zachar** [comment]
Hi @vnarni 

The available overflow options allow you to modify text at the end of the string but not the beginning.

[example](https://jsfiddle.net/0eot5hf8/1/)
[documentation](https://rdkcentral.github.io/Lightning/docs/textures/text)

Best regards

**Comment by g-zachar** [comment]
Adding to that, best way is just to manually check size of input string and determine the final output.

If you still have any further questions, please reopen.
