### ISSUE TITLE
WebGLShader VertexAttribPointerOffset wrong index ?

### ISSUE THREAD

**Issue by hacketo** [rdkcentral/Lightning#199]
Hi, 
I have an issue using the OutlineShader, I found that since commit e16ae522a9c657d6c48cc22f1eb436f4a72ffe08 it does not work properly.
I updated the WebGLShader to correct a possible miss in that commit, see 7e3c2768e8ba22797dc94bd152067056fc924c74 . 
Does this make sense ?

**Comment by g-zachar** [comment]
Hi @hacketo,

Can you give a bit of description of what you see as a problem in OutlineShader's behaviour? Also, thanks for contributing.

Best regards

**Comment by hacketo** [comment]
Before and after the 'cleanup' commit
![Capture d’écran 2020-07-10 à 13 20 31](https://user-images.githubusercontent.com/1191874/87149266-2fc9ac00-c2b0-11ea-97c9-23ebfd6c6a65.png)

My commit make it work again, it seem that the offset is off by 1 and impact other shaders. But i'm no expert about WebGL.

Best regards

**Comment by g-zachar** [comment]
Hi @hacketo,

Very nice find. It turns Dithering and Pixelate shaders were also broken for some time and unnoticed. The change is correct and the fix will be in next release. Thanks a lot for contributing!

Best regards
