### ISSUE TITLE
Transitions and Textures

### ISSUE THREAD

**Issue by rolandoamarillo** [rdkcentral/Lightning#202]
Hi there, 

I'm trying to make a really good looking animation and I'm wondering if it's possible to use transitions with texture values/params. 

Thank you!

**Comment by g-zachar** [comment]
Hi @rolandoamarillo 

I'm not sure I understand your question. Can you be more specific?

Best regards

**Comment by rolandoamarillo** [comment]
Hi @g-zachar 

Thanks for the response.

Basically, I want to create a custom texture that contains an animation or transition. Is this possible? I have tried to animate a texture with a simple image by updating the size and position of the image inside the canvas (I'm calling the _changed() method after updating the params), the _getSourceLoader() method is called just once after completing the animation or transition and it gets updated but it doesn't do it smoothly.

I'm wondering if it's possible to add some animation or transition to a custom texture without a component. 

Best Regards

**Comment by g-zachar** [comment]
Hi @rolandoamarillo 

Can you explain exactly what you're trying to implement? I can't see the reason why you would want to  operate on texture level rather than component.

Best regards

**Comment by rolandoamarillo** [comment]
Hi @g-zachar,

Yes, I'm trying to create a triangle with a canvas and draw an image inside that triangle. Also, I want to be able to resize, move with the animation/transition that image inside the triangle.

Best Regards

**Comment by rolandoamarillo** [comment]
Closing issue. The best option here to implement what I need is a custom shader. Thanks for the help.
