### ISSUE TITLE
Question: Is there a way to perform a text marquee with Lightning?

### ISSUE THREAD

**Issue by SmithAF** [rdkcentral/Lightning#204]
I'm trying animate text in Lightning like this https://codepen.io/jamesbarnett/pen/kfmKa but I have not been able to achieve a good result yet. If anyone has a recommendation on how I could achieve this that would be wonderful!

**Comment by g-zachar** [comment]
Hi @SmithAF,

please check out this [example](https://jsfiddle.net/nuq7fdc1/) and let me know if you have further questions.

Best regards

**Comment by SmithAF** [comment]
@g-zachar That's perfect! Thanks!
