### ISSUE TITLE
Using assets from external modules

### ISSUE THREAD

**Issue by lewispeel** [rdkcentral/Lightning#211]
Currently all assets have to be in the `static` directory of the application in order to be included in the build. If we have an external component library that has its own images/fonts etc... how can we include them? As a workaround we have a post install script that copies assets from the external library into the application static directory, although this doesn't feel like the correct solution.

I understand Lightning uses Rollup, would it be possible to use https://github.com/rollup/plugins/tree/master/packages/image to do something like this?

```
import icon from './icon.png'

export default class App extends lng.Component {
  static _template() {
    return {
      Icon: {
        src: icon,
      },
    }
  }
}
```

**Comment by g-zachar** [comment]
Hi @lewispeel,

are you using a bootstrapper on top of Lightning app e.g. [SDK](https://github.com/rdkcentral/Lightning-SDK) or is it just raw Lightning?

Best regards

**Comment by lewispeel** [comment]
We're using the SDK as it comes by default when using `lng create` from the CLI tools for our apps. So when requesting images we're doing this;

```
import { Lightning, Utils } from 'wpe-lightning-sdk';

export default class Background extends Lightning.Component {
  static _template() {
    return {
      Background: {
        w: 1920,
        h: 1080,
        src: Utils.asset('images/bg.png'),
      },
    };
  }
}
```

Although we have a component library which is external to the main app that uses raw Lightning.

**Comment by lewispeel** [comment]
The images from the component library are being exported as Base64 encoded images, so I guess the question is, can Lightning handle an image `src` like...

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAClUlEQVRYhe2YW47VMAyGf6c9zAtCggXAJuYFJNDsARYAi2UDbIB5RPA2EkIwnRhlektdO02alicsVc3Jxfn620l6iv9WaXS2gMxcNUc1YC3AlrkznR9hu56+QLVqdYsdJOBK67OsrRmcYVSrYtbgAtW2fhfNm9UxA86CIqWuGHBPiDXnGkAK0KpbWW0O5qq3W0GzoxJaTRFSypaaJZChjWEpuLHPWaFLqSYPhJwDgkzADShZ5zJUs/psWg6gpoyVa24j5Kk61fYoqAGQCJvbaEv5XVjJKs5Jfk1hWXaGP9UWgGJxpDZoTR0nlJNlDVLOtZpzbw5qjmUYLVjZ9/AclPUxgAYFBdBKj92AEA4tKAu4MRTchCxR0FoM8aRxaNsIjiNIZ+TgLgVLjy4n2sa7VDD20wzj2uHeRPdmAixcwaPJxRDXNyLUcd8nAF4DuAb4JUDPAFzND8LTuJSCluypE8NFcHHfSEH/DqD3gH8+RHoEcvM9XNSEptIczDlRrH3QAd1HADcI0SJi4AFDfnr0Jf8ISUT9M3VJBXPBLchlWP39JzjcTCN7yDvA3QL4DrhfIHRLEdqqN2pLOQXw91s4ipTzDLp8AZqv43vfiD2pmXofNIA0uNSYof3PBYwP09yMAPcZaH4IMAmKXMCcB0io2L0B8GLuHZRrJdzoh4Vv3rNRa2VtcfTtnq9nL+4OuGhhjeEWkGd+m+mBqXuFkHbhYrodcmyllALHRwBqx9/SPD3tc+8hbLvfIsW8yL3TcjANTv5qrnY/IyhSwrsCPRpwnZ/EPGHA3RtAFuAhf9xT200fWs8ER2NPdTFYdvbXrVkgzyHjLShNVTojxDrgDCZzb7SwYNRc/AeAjy8EAYGEgqmtpocF8BcFmKRYLP/0xwAAAABJRU5ErkJggg==`

**Comment by g-zachar** [comment]
Hi @lewispeel,

for help with bootstrapping your application you should use [SDK page](https://github.com/rdkcentral/Lightning-SDK). As for your question, currently Lightning does not support base64 encoded images but that's definitely something that should be considered for the future.

Best regards

**Comment by michielvandergeest** [comment]
hey @lewispeel, thanks for your questions / suggestions 👍

> I understand Lightning uses Rollup, would it be possible to use https://github.com/rollup/plugins/tree/master/packages/image to do something like this?

Yeah, the Lightning-CLI bundles the App using Rollup. Currently we don't have anything in place to bundle images into that as well. I will checkout this plugin to know what it really does under the hood, and see if it's anything we can use in our config.

As a side note, in case you weren't aware: in your App you can reference the `node_modules` folder by using a `~`, so you could do something like: `import Lib from '~/package123/dist/lib.js` (or `import Icon from '~/package/assets/icon.png`)

> The images from the component library are being exported as Base64 encoded images, so I guess the question is, can Lightning handle an image src like...

It indeed won't work to just assign the `src` of an Image texture with a Base64 string. But it's definitely possible to use base64 images in Lightning. You could try something like this:

```
const base64Data =
 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAClUlEQVRYhe2YW47VMAyGf6c9zAtCggXAJuYFJNDsARYAi2UDbIB5RPA2EkIwnRhlektdO02alicsVc3Jxfn620l6iv9WaXS2gMxcNUc1YC3AlrkznR9hu56+QLVqdYsdJOBK67OsrRmcYVSrYtbgAtW2fhfNm9UxA86CIqWuGHBPiDXnGkAK0KpbWW0O5qq3W0GzoxJaTRFSypaaJZChjWEpuLHPWaFLqSYPhJwDgkzADShZ5zJUs/psWg6gpoyVa24j5Kk61fYoqAGQCJvbaEv5XVjJKs5Jfk1hWXaGP9UWgGJxpDZoTR0nlJNlDVLOtZpzbw5qjmUYLVjZ9/AclPUxgAYFBdBKj92AEA4tKAu4MRTchCxR0FoM8aRxaNsIjiNIZ+TgLgVLjy4n2sa7VDD20wzj2uHeRPdmAixcwaPJxRDXNyLUcd8nAF4DuAb4JUDPAFzND8LTuJSCluypE8NFcHHfSEH/DqD3gH8+RHoEcvM9XNSEptIczDlRrH3QAd1HADcI0SJi4AFDfnr0Jf8ISUT9M3VJBXPBLchlWP39JzjcTCN7yDvA3QL4DrhfIHRLEdqqN2pLOQXw91s4ipTzDLp8AZqv43vfiD2pmXofNIA0uNSYof3PBYwP09yMAPcZaH4IMAmKXMCcB0io2L0B8GLuHZRrJdzoh4Vv3rNRa2VtcfTtnq9nL+4OuGhhjeEWkGd+m+mBqXuFkHbhYrodcmyllALHRwBqx9/SPD3tc+8hbLvfIsW8yL3TcjANTv5qrnY/IyhSwrsCPRpwnZ/EPGHA3RtAFuAhf9xT200fWs8ER2NPdTFYdvbXrVkgzyHjLShNVTojxDrgDCZzb7SwYNRc/AeAjy8EAYGEgqmtpocF8BcFmKRYLP/0xwAAAABJRU5ErkJggg=='

    this.tag('MyImage').texture = Lightning.Tools.getCanvasTexture((cb, stage) => {
      const img = new Image()
      img.src = base64Data
      img.onload = () => {
        const canvas = stage.getDrawingCanvas()
        canvas.height = img.naturalHeight
        canvas.width = img.naturalWidth
        const ctx = canvas.getContext('2d')
        ctx.drawImage(img, 0, 0)
        cb(null, canvas)
      }
    })
```

I've put this on the bag log to add either to Lightning Core, or to make make this functionality available via a helper in the Lightning SDK.

**Comment by lewispeel** [comment]
Thanks Michiel,

I've create a pull request to allow the use of image imports via Lightning CLI - which should solve our problems; https://github.com/rdkcentral/Lightning-CLI/pull/80

If this is merged I can forget about using Base64 images for this usecase (although I guess that's still useful).

Thanks,
Lewis
