### ISSUE TITLE
Question: Example for using SpinnerShader

### ISSUE THREAD

**Issue by vnarni** [rdkcentral/Lightning#223]
Hi There,
As part of 1.10.0, there is SpinnerShader. Would it be possible to provide an example to use. I tried using it with no success. 

Thanks!

**Comment by g-zachar** [comment]
Hi @vnarni,

check this out: https://jsfiddle.net/uoyjd0k2/

I hope to put some more extensive change log of recent Lightning updates in the near future that will also include examples.

Best regards

**Comment by vnarni** [comment]
@g-zachar thanks for the example. 
including examples would really help. Appreciate your help !
