### ISSUE TITLE
Setting `crossOrigin: "Anonymous"` attribute on Images causes CORS issues on some platforms

### ISSUE THREAD

**Issue by Moussa** [rdkcentral/Lightning#226]
We're testing a Lightning application on the PS4 and have run into an issue where images fail to load from some domains. Our image endpoints responses include the required `Access-Control-Allow-Origin: *` header for CORS but for some reason the PS4 browser still fails to load the images. We do not see this issue when running in any other browser, so we do not believe it's any configuration issue. It's just the PS4 browser security behaviour is unusual and unfortunately we don't have control over this behaviour.

We have verified that removing the `crossOrigin` attribute on images resolves the issue on the PS4 and so we're proposing that we add a stage option to disable adding this attribute for these problematic platforms. I will PR the changes.

**Comment by g-zachar** [comment]
Fixed with #231.
