### ISSUE TITLE
RoundedRectangleShader wrong uniform strokeColor, fillColor and stroke values 

### ISSUE THREAD

**Issue by julien-tanguy-wiztivi** [rdkcentral/Lightning#234]
RoundedRectangleShader strokeColor, fillColor and stroke values should be passed as Float32Array to avoid exceptions.

https://github.com/rdkcentral/Lightning/blob/8f33c716038e08c4afc67f2d1ef42f12b42aad97/src/renderer/webgl/shaders/RoundedRectangleShader.mjs#L75-L76

**Comment by g-zachar** [comment]
Resolved by #235.
