### ISSUE TITLE
Expected behaviour of Async functions in the template

### ISSUE THREAD

**Issue by dale976** [rdkcentral/Lightning#237]
Hi,

Is it possible to explain the expected behaviour of the async functions in the template. I'm unable to find documentation and we in our team feel that the expected behaviour is different from how it's currently implemented.

When using the async functions, the callbacks from these functions are executed after all of the components lifecycle events have been fired. We encountered this when trying to perform actions on a components position in a lifecycle event but noticed that the values were either 0 or would return the actual async function. We were trying to perform an animation on a value which was being return as a function so this completely broke.

I've attached a very basic version where you can see that in the template the width and height are used at the root of the template and all other components are using the async functions for these values. In the _init function I am printing out the value so you can see the results.

I would expect that the async functions would be executed prior to the lifecycle events being fired but it is the other way around. 

Could you please clarify what is the expected behaviour?

```javascript
import { Lightning, Utils } from 'wpe-lightning-sdk'

export default class App extends Lightning.Component {
  static getFonts() {
    return [{ family: 'Regular', url: Utils.asset('fonts/Roboto-Regular.ttf') }]
  }

  static _template() {
    return {
      w: 1920,
      h: 1080,
      Background: {
        w: w => {
            console.log('Background Async Fired (W): ', w)
            return w;
        },
        h: h => {
            console.log('Background Async Fired (h): ', h)
            return h;
        },
        color: 0xfffbb03b,
        src: Utils.asset('images/background.png'),
      },
      Text: {
        mount: 0.5,
        x: x => {
            console.log('Text Async Fired (X): ', x)
            return x / 2;
        },
        y: y => {
            console.log('Text Async Fired (Y): ', y)
            return y / 2;
        },
        text: {
            text: "Async function example",
            fontFace: 'Regular',
            fontSize: 64,
            textColor: 0xbbffffff,
        },
      },
        Logo: {
          w: 250,
          h: 250,
          x: 1920 / 2,
          y: h => h / 3,
          mount: 0.5,
          src: Utils.asset('images/logo.png')
        }
    }
  }

  _build() {
      this._background = this.tag('Background')
      this._text = this.tag('Text')
      this._logo = this.tag('Logo')
  }

  _init() {
      console.log('Background (W) :', this._background.w)  // This value will be 0 at this point as the async function for W has not been completed
      console.log('Background (H) :', this._background.h) // This value will be 0 at this point as the async function for W has not been completed
      console.log('Text (X) :', this._text.x) // This will return the async function. Trying to perform any action on this value will be invalid
      console.log('Text (Y) :', this._text.y) // This will return the async function. Trying to perform any action on this value will be invalid
      console.log('Logo (X) :', this._logo.y) // This will return the async function. Trying to perform any action on this value will be invalid

      // Now if i attempt to animate the logo on the Y axis it will fail and not render as I am trying to use the Y value which at this point is a function
      // rather than a number.
      this._logo.setSmooth('y', 900, { duration: 10 })

      // Instead if i force the Y position without using an animation it will work as I am replacing the async function with a number
      // this._logo.y = 900 <-- This will work, you must comment out line 67 though!
  }
}
```

**Comment by g-zachar** [comment]
Hi @dale976,

According to [documentation](https://rdkcentral.github.io/Lightning/docs/renderEngine/elements/positioning):

> You can use a numeric value (in pixels), but it is also possible to specify a function that returns the value based on the parent's width (x, w) or height (y, w). These functions will only be called again if the parent's dimensions (might) change.

There are 4 properties that can have a function assigned to them instead of a value: `x`, `y`, `w` and `h`. The function will be called internally with either parent's width (for `x` and `w`) or height (for `y` and `h`) as argument and should return child's final value, e.g:
```javascript
{
  w: (parent_w) => parent_w / 2 // child's width should always be half of its parent,
  x: (parent_w) => parent_w / 2 // child's x should always be positioned in the middle
}
```

This means they can be used when you want your element to be positioned or have size in some relation to its parent's dimensions ([example](https://jsfiddle.net/kxq04cbw/1/))

Now, when it comes to [animation](https://rdkcentral.github.io/Lightning/docs/animations/action_value):
>Every action should have a `v` property specified, which defines the value that is applied to the action property during the animation.
>
>You can specify:
>
> * a fixed value ({p: 'visible', v: true, rv: false})
> * a function ({p: 'alpha', v: (p => Math.sqrt(p)})
> * a literal value object, defining the value several progress control points

Since in your case `y` is a dynamic function it cannot be used by animation handler (it cannot interpolate values of a function).

Possible solution to your problem would be wrapping your logo in additional element and have it fixed `y` while relative position would be maintained by the wrapper, e.g:

```javascript
  LogoWrapper {
    x: 1920 / 2,
    y: h => h / 3,
    Logo: {
      y: 0,
      w: 250,
      h: 250,
      mount: 0.5,
      src: Utils.asset('images/logo.png')
  }
}
```

Let me know if you have any further questions.

Best regards

**Comment by dale976** [comment]
Hi @g-zachar , 

Thanks for taking the time to give a detailed response and example.
