### ISSUE TITLE
ES5 bundle produces ES6 code in runtime

### ISSUE THREAD

**Issue by victor-wm** [rdkcentral/Lightning#242]
The template parser generates a series of javascript instructions to be executed by `new Function()` and the code present there can contain the `const` keyword which is not valid ES5.

See:
https://github.com/rdkcentral/Lightning/blob/master/src/application/Component.mjs#L122
https://github.com/rdkcentral/Lightning/blob/master/src/application/Component.mjs#L125
https://github.com/rdkcentral/Lightning/blob/master/src/application/Component.mjs#L142
https://github.com/rdkcentral/Lightning/blob/master/src/application/Component.mjs#L149

Even when the code is transpiled to es5 (in lightning.es5.min.js) the strings are left intact.

**Comment by victor-wm** [comment]
Same applies for the StateMachine.

See:
https://github.com/rdkcentral/Lightning/blob/master/src/application/StateMachine.mjs#L457

**Comment by g-zachar** [comment]
Hi @victor-wm,

thanks for reporting, this is indeed an issue. What browser are you using? There seem to be scarcity of browsers that don't have basic support for `const` binding, hence the issue went unnoticed until now.

Best regards

**Comment by victor-wm** [comment]
That report came from code analysis only. I can imagine old devices such as Tizen 2.3.0 or limited settop-boxes would suffer from this.
