### ISSUE TITLE
Exception in `C2dTextureTintManager#gc` when `aggressive = true`

### ISSUE THREAD

**Issue by Moussa** [rdkcentral/Lightning#246]
The offending line is: https://github.com/rdkcentral/Lightning/blob/b17dedcdeea6301f2ffe4e95d5290be071a20be0/src/renderer/c2d/C2dTextureTintManager.mjs#L128

as `clear()` is an undefined function on textures. I believe this may be a typo and this line should actually be `cache.clear()`.

**Comment by g-zachar** [comment]
Hi @Moussa 

you are correct, thanks for contributing.

Best regards

**Comment by g-zachar** [comment]
Resolved by #246
