### ISSUE TITLE
New lines are not rendered as expected

### ISSUE THREAD

**Issue by achille1789** [rdkcentral/Lightning#277]
Hi
In one string I was trying to use more new lines (\n\n) one after the other one and only the first one is rendered.
I need to put an extra space between them (\n \n) to have them rendered correctly.

**Comment by g-zachar** [comment]
Hi @achille1789 

This should have been addressed in 2.2.0 release (#267)

Let me know if you still have any issues.

Best regards

**Comment by achille1789** [comment]
Yes, that works. Thanks.
