### ISSUE TITLE
bindProp is not working with the `text` shorthand

### ISSUE THREAD

**Issue by victor-wm** [rdkcentral/Lightning#283]
Hey all, when using `bindProp()` to return a bound `text` texture property one would expect it to work with this syntax:

```
public static _template() {
  const boundText = this.bindProp('text', (ctx) => {
    return { text: ctx.text, color: ctx.color }
  });
  
  return {
    SomeComponent: {
      text: boundText
    }
  }
}
```

Lightning seems to ignore the property completely, probably due to the way it parses shorthand properties for `text`.

Any thoughts?

**Comment by g-zachar** [comment]
Hi @victor-wm,

You should use unique property names for bindings, `text` as you noticed is one of component's reserved properties.

Proper usage would be something like this:
```
static _template() {
  return {
    SomeComponent: {
      text: {text: this.bindProp('myText'), color: this.bindProp('myTextColor')}
    }
  }

 _init() {
    this.myText = 'some text';
    this.myTextColor = 0xff112233;
 }
```
You should also be wary of binding whole objects as there are no sophisticated mechanisms that would detect when properties of those objects change.


We could consider expanding functionality of `text` property a little bit to support syntax such as:

```
text: this.bindProp('myTextObj')

this.myTextObj = {text: 'example', textColor: 0xff112233}
```

Best regards

**Comment by victor-wm** [comment]
Hey @g-zachar, thanks. 

`text: this.bindProp('myTextObj')` is exactly what I'm looking for. And from what I read in source, moving the binding logic before the `text` property parsing would do the trick.
