### ISSUE TITLE
Accessibility / screen reading

### ISSUE THREAD

**Issue by elsassph** [rdkcentral/Lightning#284]
Is there any screen reading functionality? It's a requirement for some apps on Tizen and I believe an option on Rdk.

**Comment by g-zachar** [comment]
Hi @elsassph 

Could you elaborate on what you're looking for a little bit more?

Best regards

**Comment by elsassph** [comment]
https://developer.samsung.com/SmartTV/develop/develop/guides/fundamentals/accessibility.html

https://developer.samsung.com/SmartTV/develop/develop/guides/fundamentals/text-to-speech.html (this is ARIA, but it also supports HTML5 speech synthesis).

**Comment by g-zachar** [comment]
Hi @elsassph 

The links you provided unfortunately don't work for me, but I get the idea. We usually implement those as feature requests (e.g. recently added magnifying shader - which is not released yet but part of master - you can check out [this example](https://github.com/rdkcentral/Lightning/blob/master/examples/shaders/magnifier/magnifier.html)). Some of them are not fit to be in lightning core, but it is possible they could be in [SDK](https://github.com/rdkcentral/Lightning-SDK) or build as third party libraries elsewhere. Answering your question, there are no accessibility functionalities in lightning core itself.

Best regards

**Comment by elsassph** [comment]
Ok this is super odd... Using search on the Samsung website I can find the pages but they are oddly 404 when linking it them...

Thanks for the answer anyway.
