### ISSUE TITLE
Text block height differs from DOM-rendered output

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning#286]
Given this config
```js
text: {
  fontSize: 20,
  lineHeight: 30,
  text: 'Test'
}
```
Lightning will render text block with height of `40px` in FHD. It seems like this line in `TextTextureRenderer` adds that redundant 10 pixels making text blocks rendered with Lightning to look different from regular DOM output: https://github.com/rdkcentral/Lightning/blob/282939f1d81e1bf6eec527180a69745c4b17d9bf/src/textures/TextTextureRenderer.mjs#L219
It causes multiple issues since we could not follow UI specs for our apps.

**Comment by g-zachar** [comment]
Hi @Serhii-the-Dev,

this is partially related with [canvas text baseline](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline) set to `alphabetic` by default and remaining so for backwards compatibility. We can merge the fix but it will require you to use `textBaseline: 'bottom'` in your apps. Let me know if such solution satisfies you.

Best regards

**Comment by Serhii-the-Dev** [comment]
Hi @g-zachar,

I've just checked #290, works just as expected. Multiline text also works as expected, so we don't need to override the `TextTexture` anymore. Thank you very much for such a quick fix!

**Comment by Serhii-the-Dev** [comment]
@g-zachar is there any chance to see this fix in a next Lightning release(btw, what release cycle Lightning uses)?

**Comment by g-zachar** [comment]
@Serhii-the-Dev I'm pushing for next release atm. New Lightning releases are made every now and then once there are enough changes (usually several features/bugfixes).
