### ISSUE TITLE
Img loader error on 

### ISSUE THREAD

**Issue by NickLeDev** [rdkcentral/Lightning#291]
Hello,

I'm a developer working on a Xfinity Comcast device project and I have issues with the Img plugin.
I'm using an endpoint for my lightning app to consume and it feeds a. lineup of items that have each an image to display. I read in your documentation that when it's from an Api I should use the[ Img plugin](http://www.lightningjs.io/docs/#/lightning-sdk-reference/plugins/image). Everything works fine in dev (latest Chrome) but when I go on the Comcast device I have only some images that are displaying. It's always the same every-time I reload.

Here's the error I get:
```
[Lightning] texture load error Image load error https://images.tou.tv/c_scale,w_223,h_125/v1/ici-tou-tv/promos/16x9/764baab2-2c66-6126-3855-369d9ffc053b.jpg-contain-375-210.9375

texture failed to load: https://images.tou.tv/c_scale,w_223,h_125/v1/ici-tou-tv/promos/16x9/764baab2-2c66-6126-3855-369d9ffc053b.jpg
```

As you can see there's something that is added at the end of the url in the first error (-contain-375-210.9375).

Like I said, I have this issues on around 95% of my images and the others are working properly.

Here's a bit of code inside my component Card that is using the Img plugin

```
_init() {
		this.tag('Image').on('txLoaded', () => {
			console.log('texture loaded: ' + this.tag('Image').texture.src)
			this.tag('Image').setSmooth('alpha', 1)
		})

		this.tag('Image').on('txError', () => {
			console.error('texture failed to load: ' + this.tag('Image').texture.src)
		})

		this.tag('Image').on('txUnloaded', () => {
			console.log('texture unloaded!')
		})
	}

	_active() {
		this.tag('Image').patch({
			smooth: {
				alpha: 1,
			},
			texture: Img(this.image).cover(this.w, this.tag('Header').h),
		})
	}
```

**Comment by g-zachar** [comment]
Hi @NickLeDev,

If this is device specific problem it's gonna be hard for me to debug. Does the error occur only to images with url suffix you mentioned?

Best regards

**Comment by NickLeDev** [comment]
Hi @g-zachar,

Actually yes I tested it on multiple browser and it works fine but on that device. I know it might not be easy to debug without having the device.

The original images don't have the suffix and the bug happens only on those. Is it Lightning that is adding the suffix while working on the image to render it?

Thanks for your help!

**Comment by g-zachar** [comment]
Hi @NickLeDev,

I just noticed you're using Lightning-SDK's `Img` utility (https://github.com/rdkcentral/Lightning-SDK/blob/master/src/Img/index.js). Your platform may have problems accessing the image server that the utility uses. You can either scrap the image server altogether if it's not necessary (just use [src](http://www.lightningjs.io/docs/#/lightning-core-reference/RenderEngine/Textures/index) shorthand for your images) or pursue the issue further in Lightning SDK's [repository](https://github.com/rdkcentral/Lightning-SDK).

Best regards

**Comment by NickLeDev** [comment]
Hi @g-zachar,

Thank you, I'll try this and I'll pursue on the other repository.

Closing this issue!
