### ISSUE TITLE
Text is blurry after scaling to 720p

### ISSUE THREAD

**Issue by AndriyShpyra** [rdkcentral/Lightning#299]
After automatically autoscale on Comcast devices, we have observed that text becomes blurry.
For example: 

720p
![720p](https://user-images.githubusercontent.com/49644516/117294180-069b8d00-ae7b-11eb-8df9-ae4d603537dc.png)

1080p
![1080p](https://user-images.githubusercontent.com/49644516/117294276-216e0180-ae7b-11eb-9f52-9e87f44359ff.png)

Is there a way to fix this behavior?

**Comment by g-zachar** [comment]
Hi @AndriyShpyra,

what are the sizes of the fonts you're using? Are you experiencing same issue on desktop browser as well?

Best regards

**Comment by AndriyShpyra** [comment]
Hi @g-zachar ,

The sizes are 32px and 24px;
After setting the 1280x720 resolution on the desktop browser via dev tools, 
we experience the same issue

**Comment by g-zachar** [comment]
Hi @AndriyShpyra ,

can you test this fix (https://github.com/rdkcentral/Lightning/tree/fix/text-texture-blur) and tell me if it solves the issue for you?

Best regards

**Comment by AndriyShpyra** [comment]
Hi @g-zachar 

I have tested the application with the changes from (https://github.com/rdkcentral/Lightning/tree/fix/text-texture-blur) .
On 720p I didn't notice any changes.

Also, previously, we were using `rtt` property on the parent component, which was wrapping text texture. 
After we removed the `rtt` property, the text quality became better. But still the original 1080p text textures have better quality

**Comment by g-zachar** [comment]
This is my side by side comparison of the fix:
<img width="364" alt="Screenshot 2021-06-08 at 09 37 10" src="https://user-images.githubusercontent.com/52450609/121395523-d00dd200-c952-11eb-9109-f4c44f1765b5.png"><img width="373" alt="Screenshot 2021-06-08 at 09 36 51" src="https://user-images.githubusercontent.com/52450609/121395515-cdab7800-c952-11eb-94e3-abc44e879582.png">
The quality will not be as good as 1080p, but the difference should be noticeable. Are you using `canvas2d: true` setting by any chance?

**Comment by AndriyShpyra** [comment]
@g-zachar, sorry for the late response.
Yes, I created the new Lightning application and I see the changes with text texture.
Thank you!
