### ISSUE TITLE
Dispatching events from outside Lightning

### ISSUE THREAD

**Issue by danvoyce-warner** [rdkcentral/Lightning#322]
I'm trying to add some tests to our app that checks the correct item is focused after pressing various (LRUD) keys.

I'd like to be able to trigger a native event to do this, however it doesn't seem possible, even from within the browser.

I thought I could do something like this after seeing [this line of code](https://github.com/rdkcentral/Lightning/blob/master/src/platforms/browser/WebPlatform.mjs#L202)

```js
    const event = new KeyboardEvent('keydown', {
      keyCode: 37 
    });

    window.dispatchEvent(event);
```

Any suggestions?

**Comment by g-zachar** [comment]
Hi @danvoyce-warner 

This should be possible, please check this example and let me know if you have further questions:
https://jsfiddle.net/s1zmtgkv/

Best regards

**Comment by danvoyce-warner** [comment]
Thanks for the speedy response and example @g-zachar! I'm doing the exact same thing and it's not working. Can't see why, but going to keep digging!

**Comment by erikhaandrikman** [comment]
@danvoyce-warner is it not working on your local machine? Or on another device?

**Comment by danvoyce-warner** [comment]
On my local device. The example works fine though.

There's quite a lot going on in our app so quite likely something is getting in the way. Not sure what yet as I'm not too familiar with the codebase.

**Comment by danvoyce-warner** [comment]
This was the culprit 😅

```ts
public _captureKey(value: KeyboardEvent): boolean {
    const isTrusted: boolean = value.isTrusted || false;
    if (!isTrusted) {
      return true;
    }
   ....
```
