### ISSUE TITLE
Lightning shows black area while rendering large size image

### ISSUE THREAD

**Issue by AJpandher10** [rdkcentral/Lightning#360]
Hi,
I was using clipping tool to show a large image of 64,000px width but lightning throws following error and black area while rendering.
> WebGL: INVALID_VALUE: texImage2D: width or height out of range
> WebGL warning: texImage: Requested size at this level is unsupported.
 
Is there any other way for doing that in lightning?
I was able to do get results while using DOM  and css clipping , is this approach acceptable ?

**Comment by g-zachar** [comment]
Hi @AJpandher10 

Currently there is no support for very large textures, in fact the limitations are directly imposed by the platform. You could split the image into set of smaller textures and manage them manually if you are determined.

> I was able to do get results while using DOM and css clipping , is this approach acceptable ?

As long as you are using standard HTML/CSS to a limited extent, there shouldn't be any negative implications. Once the number of DOM elements grow, the performance will likely decrease significantly.
