### ISSUE TITLE
Feature request: ordered list for texts

### ISSUE THREAD

**Issue by Devjeel** [rdkcentral/Lightning#365]
Q: Is it possible to have bullet points list feature for ordered list?

for now we have to add bullet point uni char in string, which is not the best way. Any other alternatives possible?

**Comment by g-zachar** [comment]
Hi @Devjeel 

Theoretically, it is possible, but in practice, it would be hard to come up with an implementation for lists robust enough to satisfy most use cases.

Using Unicode characters is currently the best way to approach it.

Best regards
