### ISSUE TITLE
Rounded rectangle with shadow

### ISSUE THREAD

**Issue by Marine-Dos-Wiztivi** [rdkcentral/Lightning#368]
I do not succeed to make shader with rtt and shadow work together.

Here I am trying to create a disk composed of 2 rectangles of 2 colors, with a shadow: https://jsfiddle.net/rsh05o36/1. If I do not set rtt to true, shader is not apply on rectangle, but if I set rtt to true, shadow disappear. I have the same issue with other shaders, here with a fadeOut : https://jsfiddle.net/rsh05o36/3/.

Is there a way to achieve that ? Setting shadow outside the rect with rtt would solve the case of rounded border shader but not the one with fadeOut.
Or is there a way to apply multiple shaders on the same level and use a shader for shadow also ? Or is it due to the size of my element and the fact that the shadow is outside ?

Thanks

**Comment by g-zachar** [comment]
Hi @Marine-Dos-Wiztivi,

Is this what you're after? https://jsfiddle.net/ap8vm96o/
Once you set `rtt` on an element its texture is essentially clipped to its width and height upon rendering.

Best regards

**Comment by Marine-Dos-Wiztivi** [comment]
Hi @g-zachar,

I would have liked to not change the size of the texture. But as you confirmed that `rtt` will clip to its width and height, I won't really have the choice.

Thanks a lot
