### ISSUE TITLE
Lightning applications abuse requestAnimationFrame API

### ISSUE THREAD

**Issue by jacek-manko-red** [rdkcentral/Lightning#380]
Lightning applications are using requestAnimationFrame to keep repainting the screen, even when the application is idle and new frames are no different than the previous one.

This is causing performance issues on Liberty's Apollo platform, visible especially when e.g UI popup is shown above wpe's surface.

requestAnimationFrame is intended mostly for animations. When there's nothing to refresh, then the application should stop repainting. This can be achieved in multiple ways:
- [cancelAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame) API
- proper logic in the callback, e.g:
function RAFCallback(timestamp) {
  if (shouldRepaint) {
    repaint();
  }
  requestAnimationFrame(RAFCallback);
}
- similiar to the above, stop calling RAF on some condition and resume later when needed

**Comment by lmatteis-wm** [comment]
As far as I know indeed the requestAnimationFrame callback is called continuously even on idle, but actual work is only done if there are updates in the tree: https://github.com/rdkcentral/Lightning/blob/master/src/tree/Stage.mjs#L289

**Comment by jacek-manko-red** [comment]
Right... but it turns out that RAF on wpe has a side-effect of continuously pushing frames to compositor, even if nothing is done in RAF callback.
Here's my PR which fixes that issue:
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/870

**Comment by jacek-manko-red** [comment]
Please see the comments in the PR above. Can you get this fixed on Lightning side by only scheduling RAF when necessary?

**Comment by wouterlucas** [comment]
Hi @jacek-manko-red,

Can you let me know if this remedies the issue you are having?
https://github.com/rdkcentral/Lightning/commit/feea99bef44ac282caeb4b615ab9d6e99e1912b5

We're looking for some feedback whether or not the above works :)

**Comment by jacek-manko-red** [comment]
Hi @wouterlucas 
Sure, but to test that I'd need access to some app deployed with Lightning version containing this change

**Comment by wouterlucas** [comment]
Absolutely, try:
https://github.com/wouterlucas/com.metrological.app.TMDB/tree/feat/raf-fix-lightning

Followed by:

1. `npm install`
2. `lng build` (assuming you have the Lightning-CLI installed)
3. `cp -r lightning/* build/lib/`
4. `lng serve`

And run it on your box, let me know if that helps!

**Comment by jacek-skiba-red** [comment]
Hi, unfortunately fix is not working.

My reproduction steps:
* I fetched raf-fix-lightning branch
    * this PR is present on that branch https://github.com/rdkcentral/Lightning/commit/feea99bef44ac282caeb4b615ab9d6e99e1912b5#diff-142d4910858111883a8658b068ed323f466b8139cc7fc73aed8b484660701479
    * `pauseRafLoopOnIdle` is set to true
* `lng build` and `lng serve`
* dummy app was rendering continously FPS stats in right-upper corner, so the page was not in idle state
* I removed the code from `src/App.js:refreshLoop` https://github.com/wouterlucas/com.metrological.app.TMDB/blob/feat/raf-fix-lightning/src/App.js#L47 

Observations: 
* lightning page without animations is still constantly calling RequestAnimationFrame
* video with STB reporduction attached: [stb.webm](https://user-images.githubusercontent.com/42027818/198957733-c56e8afa-e98a-47e8-ba40-e91a8b7d42b6.webm)
    * numer of pushed frames to weston compositor is seen in `/proc/brcm/surface_compositor`
    * for each RAF call, one frame is pushed to compositor
    * having idle lighting page we all the time send frames to compositor

Issue can also be debugged on chrome with web inspector, using redering tab (which shows repainting areas in green color):
- OK reproduction for BBC iPlayer app (idle page is not green): [chrome_bbc.webm](https://user-images.githubusercontent.com/42027818/198958158-b3f0340a-66b0-40ee-933c-6eb9aa3bd984.webm)
- NOK reproduction for Lightning app (idle page is all the time green): [chrome_lightning.webm](https://user-images.githubusercontent.com/42027818/198958325-ce99c714-a9b0-408d-aac8-a2d80056afa3.webm)

**Comment by wouterlucas** [comment]
hi @jacek-manko-red 

You're right, there was an issue in 1 of the Shaders that TMDB uses. I've pushed some fixes to:
https://github.com/wouterlucas/com.metrological.app.TMDB/commits/feat/raf-fix-lightning

Please try again, I've verified the above changes and for me the RAF doesn't get called anymore after the TMDB app reaches an idle stage.

Note this may vary by application, if the app has a continuous animation or a shader issue like TMDB had it will prevent the renderLoop from being idle.

**Comment by jacek-skiba-red** [comment]
Hi @wouterlucas,

In general it's better on chrome:
* page is in idle state
* no repaint is done (seen from devtools perspective)
* but still RAF callback is all the time called in idle

Video attached: [raf_still_called.webm](https://user-images.githubusercontent.com/42027818/201315423-52e8b510-b5b4-4ab3-8d78-a3a4635eb90d.webm)

When RAF is all the time called, on our Broadcom based STB we are getting all the time compositor refresh in idle mode.

**Comment by wouterlucas** [comment]
hi @jacek-manko-red it seems you're running an older version of Lightning in the test that you've conducted. 

In the video the `pauseRafLoopOnIdle ` isnt present which indicates you did not get the Lightning update (you even searched for it). 

Please make sure you update your npm modules and do a clean rebuild of the application before testing.
For reference this line:
https://github.com/rdkcentral/Lightning/blob/35dc08544f8906c989833b0967ab54b542553085/src/platforms/browser/WebPlatform.mjs#L97

Should be present in the attached Lightning running the app or the feature wont work.

**Comment by jacek-skiba-red** [comment]
Works as expected - we don't see compositor updates when lightning page is in idle state. Thanks!

Two questions: 
* from source code it looks like `pauseRafLoopOnIdle` has value `false`, but it has value `true`. Where it's set to true?
* final working code is available starting from lightning in version 2.7.0?
