### ISSUE TITLE
"Named capture groups" feature is not widely supported and breaks old platforms

### ISSUE THREAD

**Issue by victor-wm** [rdkcentral/Lightning#387]
Hi there-

We have been trying to integrate the new version of Lightning (2.6.0) but we faced a bug that causes the app not to load on target devices, specifically older versions of Samsung Tizen and LG.

Our root cause analysis points to the `TextTextureRendererAdvanced.mjs` usage of [Named Capture Groups](https://caniuse.com/?search=named%20capture%20group) RegExp feature, which is not available in older browsers.

Would it be possible to replace that capture group to be index-based instead of named? Not entirely sure what the effort would be into modifying that text parser.

Thanks in advance

**Comment by erikhaandrikman** [comment]
Hi! Thanks for raising this issue, we've changed the implementation to make get matched group by index: https://github.com/rdkcentral/Lightning/tree/fix/text-named-groups

Let me know if the fix is working

**Comment by g-zachar** [comment]
Resolved by #394
