### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [rdkcentral/Lightning#425]
Does lightning have RTL support? Can we create a custom texture with RTL?

**Comment by g-zachar** [comment]
Hi @SatadruBhattacharjee 

can you explain exactly what you mean by RTL texture?

Best regards

**Comment by SatadruBhattacharjee** [comment]
Hi @g-zachar,
The requirement is to have an RTL layout (Right-to-Left).  For example, tried this approach but it's not doing anything. 

` <script type="module">
        //attachInspector(lng)
        import lng from '../../src/lightning.mjs';
        const TEXT = "This text is normal.\nThis text is <b>bold</b>.\nThis text is <i>italic</i>.\nThis text is <color=0xffcc2222>red</color>.\nThis text is brokennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn up.\n"

        window.onload = function() {
            class BasicUsageExample extends lng.Application {
                static _template() {
                    return {
                        text: {
                            w: 500,
                            wordBreak: true,
                            advancedRenderer: true,
                            text: TEXT
                        }
                    }
                }
            }

            const options = {stage: {w: 900, h: 900, clearColor: 0xFF000000, canvas2d: true, useImageWorker: false}, debug: true}

            const app = new BasicUsageExample(options);
            const stage = app.stage;
            stage.direction = 'rtl';
            const canvas = stage.getCanvas();
            canvas.dir = 'rtl';
            // const ctx = canvas.getContext("2d");
            // ctx.direction = "rtl";

            document.body.appendChild(canvas);
        }
    </script>`

**Comment by g-zachar** [comment]
@SatadruBhattacharjee

Unfortunately, currently there is no support for right-to-left component layout or text layout in Lightning.

Best regards

**Comment by SatadruBhattacharjee** [comment]
Thanks for your message @g-zachar , any plan to support RTL in V3 ?

**Comment by erikhaandrikman** [comment]
We will put this feature on the backlog

**Comment by frank-weindel** [comment]
@SatadruBhattacharjee I'm not sure if this is helpful or not, but have you tried using [Unicode Bidirectional control characters](https://www.w3.org/International/questions/qa-bidi-unicode-controls) to get what you are trying to achieve in Lightning 2.0?

Here's an example from our new [Lightning Playground](https://lightningjs.io/playground/#N4IgJgpgDhB2mwMYEsIGcQC5QAEA2yA5gBYAusyshAVmgPSID2AThFiGaVGpnQ2LAB0aANYBPKAENEIwZABudfETIUqtBizYAaEMpLlKNemjAj2nbr35DRE6bIVKCBtcbqmROACyCAHIIAzCAAvrpoiMzIUKQY2CB4kgCuSMSCtFigAGbIeGyYCcmp6Ri6TJDsyAC2UCykAAQAglBQ9VnMjFX1AOSCdM1QJd0A3AA6sONMsGgNjDHIjNP1ALz1wDOShBCYawDuOwCcAGwADNr1xDsArN5n9Yh5kswAwox4LDsnAB4nv3+-IRCYyQixm9UkLRW9VgEF2TRaAAo5qQFtMAJTAsCMRBJKpwUiCABGjDAYkEEJg8GexFyYARFOEpE2EEEW1Iz0ksHkkjQCLRGJAukglIQKHQWAA2iA+gMSiAALphEAACQgeHeAHUWHgwHL4jk8uxVerGFrmDq5WUSfkQNVaswGgAZFSGKhtDpdbr6VRGDRMVgjcZB2B8C6kLg8PgbGSMeQQZhZd67QRMKp0SR0ACMVwOAHYDn4jpmswcTn4AEwF8YQL72hqQLLJPANB48tD1Y2a7Vgeo10hwMDt52uIyCV41Rb4tbjeqz+obFGIeoAfX7NUS-b509gc9391BDQdeChAAMg6MkuWTuWAKLK5AAQlGF6v5ee43vT9gJ+Be7nrFIJJmB3YAZz-PdHUkQk1R2YAqkYFJSE+QQrnOL4dm8Pw7jETBy1zO5+y+JC1kI4ij3OLJFlIABlZAAC9tnqLDzlIxoXFgHZuiiAxukBMC-xCfj6kE2AQkFcBoAHOAxTiKVvVddx-TYRVdFlDJ9VyG01NKEByhtO06nqYcfTddpOh6eS3D9LRAwmCgJwdDs1S7c0ezMz0+k7U1uyGYFq1rQyGybFtEjQdsBl7IiByHF03EEAYCEQSQUUWbddwXZAl1XCB12SiAt1AndwIAoCQKE8CnJNM0dVg0gJEYrzqrAESKpaucRLEoVJPgaTUFkvQXBMxStHEzznO81y5UVJUmUJOIQEkdVQiAA).
