### ISSUE TITLE
 Bad zSorting when zIndex is the same

### ISSUE THREAD

**Issue by jorge-graca-sky** [rdkcentral/Lightning#443]
Hi, I have been investigating why some Elements randomly pop in front of other in our app. This has revealed a bug in the lightning’s zSorting algorithm, it does not sort Elements with the same zIndex by updateTreeOrder.

The issue is on sortZIndexedChildren of ElementCore, on lines 2062 “// Merge-sort arrays;” it assumes both arrays are sorted, however same zIndex items may not be (since _updateTreeOrder change does not trigger _zIndexResort = true the a array may have unsorted items)

The logic that ensured this was removed on version 1.0.4: [performance(updateTreeOrder): refactor, make simpler and (in most cas… · rdkcentral/Lightning@38285e0 · GitHub](https://github.com/rdkcentral/Lightning/commit/38285e00ef018a23f11e0943507da20f793090db)

My suggestion of fix:
https://github.com/rdkcentral/Lightning/pull/441

**Comment by frank-weindel** [comment]
Hi @jorge-graca-sky, do you have any reproduction code/steps that consistently cause the "random pop" issue? If it helps we have a playground now where you can easily build examples and share them with a link: https://lightningjs.io/playground/

**Comment by jorge-graca-sky** [comment]
Hi @frank-weindel, thanks for the quick reply! Here is the requested playground example:

1. To see the bug press left.
2. Can see the issue with _updateTreeOrder not begin sorted by pressing right (after pressing left).
3. Can fix the zSort algorithm by pressing down.

[Playground example](https://lightningjs.io/playground/#N4IgJgpgDhB2mwMYEsIGcQC5QAEA2yA5gBYAusyshAVmgPSID2AThFiGaVGpnQ2LAB0aANYBPKAENEIwZABudfETIUqtBiwg4ATIIAcggIwgANCGUlylGvTRgR7Tt178hoidNkKlBK2ts6exEcABYDQQBmEABfczREZmQoUgxsEDxJAFckYkFaLFAAM2Q8NkwM7Nz8jHMmSHZkAFsoFlIAAgBBKCh2ouZGJvaAckE6bqga4YBuAB1YeaZYNA7GFORGZfaAXnbgFclCCEw9gHcTgE4ANgAGU3biE4BWULv2xDLJZgBhRjwWE43AAeN1BYNBMRicyQmxW7UkPR27VgEFOXR6AAo1qQNssAJTQsCMRBZJpwUiCABGjDAYkECJg8G+xFKYAxDOEpEOEEER1I30ksHkkjQGLxBLM4GgcAQKHQWAA2iAxhMaiAALpxEAACQgeH+AHUWHgwGr0iUyuxdfrGEbmCa1XUaeUQM1WswOgAZFTWKh9AZDYaWVQ2DRMVgzeaLWEdACaSKMN2hSzhAA0kTok-MIED3R1IEVsngOh8RWh2tbDcawO0c6QZeXvf4bIJfi1NuS9vN2j32gccYh2gB9estTL1sVd2C9mftVikLLMafAbuztcALV+sHrQNIRhOK+na+PPaKLEQEHXAEl4DmtzvSCdSMwshBTKuT2uAMoARyyXwgJpKCyNB9ynT8IPaAAvG9ICBE4AFpEzuD9ILXeD2hQo80LXMRAXfbCcJnVhEEfdpn1fe5znaZD7keGjQXuJh-mYQEgSKDiinBAiiLXAAVZBSDKA9UN42c8KeLCxJPB8D3IusTmGJDhnaGJRN4tTCLQuJ1Ig39-1YMDD2k3sMPTAAqIweJM9o8PaeNLOskySLIii33aajaIeE4vOYgFMPYribkkSQOKc6SBKE45wJs3sJKk2Ke1kvZ5N3RSjBUzTYp0rTeP0gCjCM3TpIwp5wtiuyyuKsSXKfF93M8sE6OeN4-NYgKOPBMLqt4yLhJixLZ2S4BUrI4ZCsynqiJywaexg28MMTcqNOWoj8sMnQRNykyzMs9oAGoGNW6S7NjPbDqWqacNq8j6qonymu89pJKYv5-OBDj9C+77jrEvrouM2aZ2G0b0p0SbtukmabOh6bfuPdaIE2gaSpOCzInhiDTvMjGrpPG63Puhi3no3y3vaj7C0kUFushtD-q2oH4sxnCQeS4ZwdUvHjyylbuZ7RHIkZmyzPaczQhZk9sYl-nZwJu6PIekmldeli2I4kKQtp2KGZRirMBe2WZIUlL2ciCHstl2HP2tmdeZ7TSP3mGJJUgRlZVQNIlWDX1AnDNhNXMVUCnNUoXWD2oQHqF03TadomxDP1+kGEYfYCMMtEjBYKHbD0Kz1Kt7RrZPAzGStbWrKZoWzXM44LIsS0yNBywmWtdwbeOfQCQQJgIRBJBxTYUf7ZBBxHQCoHHCBJ0Btd50XZcrvLu0TQPUgJGi5fq3t2cd53vl85tFe2TxPXe3npdyJZNBBC5QgMWGLei+GAlUJ34diEFMAyk9CAilIGexUygdDQH+AqRgkSkGvoIJ+Do74P0RhNV+kNQEGQgIVQQ804JIiTO0PgfFr4eVKHgW6RAjjMHhNBL8bQoyQz4LqVgHkIDvE-lQZhUDmGsFvMwPirBmGUiyPmRgyJGAgIgB0Dhw4sE5gAEroDjqQYRbkgHiL7GA1gOhIHQNgaaeBwxEbg2QTJbRBcK5F1vocB+m5NgPgyniQQiAWQmm9CsekYAwCdAAaggCOh7iRCMWuYqfBNFoGIIwLIJp2iUmYUPRRvQBEdGQOWWAojiopj+Dyf498oFJJgaY4+Fj77DGsduOsdiHFOLAC4ikTdSABIdrQmcfB2gEOYVBahedJB4EICwQSxAhinGISIkBCjiBtNgjmbYNxaxlDJNucsoV6wUI4cgChWQoBgAHhAXhEAIAAHlmCQAoY4wURw0CoSHKw7+EAZE+kAZDYBai0FGE0bsHJN8dGFIQeo9BhjoTGNyZ8vRJTbEvzcWybxG16mziCXQF5fYwkRJrNE9osS1hRMEe0JJwy0mwgyYILJGJ3l5KPpXYF94ylgscayapBKRR1P+b2R2hE+AGmYf3acJQgRXzaR0nEfouk9KSFYIYlIxB9nEfywgPL2i1PaOszZ9Ydn7MORAChglAJSImUCORaAFFKPqhcq5ZQAAijBTiwHuSeR5kLmFvOgXonRYK9GIyArAECdjGVrltZg7VOCvVc1gC7cwbsZRwDlF7CwfhE5+y0JKMu+TK4FE1FqLklI0ggC6XgWIQA)

**Comment by jorge-graca-sky** [comment]
Hi @frank-weindel, is the example understandable? Anything else I could help?

**Comment by chiefcll** [comment]
@uguraslan is this fixed - I think the bug needs to be closed

**Comment by frank-weindel** [comment]
@chiefcll I don't think this bug was ever addressed.

**Comment by uguraslan** [comment]
@jorge-graca-sky suggested PR #441 as a fix, we need to review the suggested fix.
