### ISSUE TITLE
TextTexture does not handle Chinese text well

### ISSUE THREAD

**Issue by Moussa** [rdkcentral/Lightning#450]
We've observed that Chinese text within TextTextures do not line break correctly, resulting in Chinese text being rendered as a single long line that overflows the container. Perhaps Lightning should be applying https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages? We've worked around this internally by adding a space after characters defined in https://en.wikipedia.org/wiki/Chinese_punctuation, but it would be great if Lightning could handle this internally. Other non-latin languages are likely affected.

**Comment by uguraslan** [comment]
@Moussa Thank you for bringing this to our attention. To better understand the issue and reproduce it, would you be able to provide a sample app that can be created by using the [Lightning playground tool](https://lightningjs.io/playground)? It would be great if the sample app contains your work-around as well.

**Comment by Moussa** [comment]
Hi @uguraslan. Sure thing, this playground app shows the issue with some sample Chinese text. If you replace the original text input with the `parseNonLatinPunctuation` parsed input you'll see improved text rendering behaviour.

https://lightningjs.io/playground/#N4IgJgpgDhB2mwMYEsIGcQC5QAEA2yA5gBYAusyshAVmgPSID2AThFiGaVGpnQ2LAB0aANYBPKAENEIwZABudfETIUqtBiwg4ATIICcggAwgANCGUlylGvTRgR7Tt178hoidNkKlBK2ts6exEcABZBAA5BAGYQAF9zNERmZChSDGwQPEkAVyRiQVosUAAzZDw2TCzc-MKMcyZIdmQAWygWUgACAEEoKE6S5kYWzoByQTpeqDrRgG4AHVhFplg0LsY05EZVzoBeTuA1yUIITAOAdzP9ADYjU07iM4BWULvOxArJZgBhRjwWM5GAAeRlBYNBcTiCyQ2zWnUkfT2nVgEHOPT6AAoNqQtqsAJTQsCMRA5FpwUiCABGjDAYkECJg8G+xHKYAxDOEpGOEEEJ1I30ksHkkjQGLxBLM4GgcAQKHQWAA2iAJlM6iAALoJECqoqZMoVdg6+ogRqVECtdrMLoAGRU1ioAyGI1GllUNg0TFYc0WFo6nSkzDQEAActtrZIcbAAAp5RCkHIR3GO4ZjCYBoOh2DhyMxpDxxPbGbQ5awrqkCBArr7eYgQBbdrXAP6pgH0bQA4coBcBMALDaAGH-AFa2gEagwAbtoBeHUAj0GAEbTAEAMgHozQB66YAEI0ApLGAG3jACyagC8vLuAJXTAI46gFz5QDnpoAKdS7gAPFQBleoBUTUAzGmAIr8J4BfN0Ai8qAFDtAKxWTcAWHaAKDku4B7g0A0O6ANOegAQ5oApGaAHMZE6AABygBvGoAUraAEqJgA5qoAH26AEQJXaACfKgBTcoAWJqAIg6gDRcl2gC-CYAG3KAIjegAQMYAtHLTvOy7rlue5Hn+QFgZBsGIahGE4QRxH1s27bdv2w7jhOnTnted5Pm+n4-uR1E0TWxYokClpdJAJS5HgXQfCKaDov0FblvAhm2v4NiCFMBCIAWsAHIsnTOZ0Rw4ognQAPrlm02TlmKjkOS5wWsPGzAOcATnBdFzkAComWckVBTFKWdOWlaJVFqXZQM2ykAAysgABepydNE1ymFlOUpelpDdH4sBnKMiDkhAzCjJVyXVTFtWdd1qV8LVZzpiGYaJtGsb5ji2wYrVeJ9f1MXnCwYAAOrMAiq3IGApCPJ0tx3FVi3ObVvz-MwgJAiU10lKC10LYtcRHSlCTPc5T1dR9cSSpAjKyqgGRKq69qBJ6bDmGmXwZmNOaTQm01CEUmrmCNmbZpQuZxvDuJqnq5RmqjMMY3D9lqg0NJmnwnQ1hUJSkDW8KsJ0RCwFoYDwoZ5wQJ0RKwKMXTnIKZaMJ0lKsJIIidNsaXEBALQlqsXQlDkeB4FtO3EJjU1JvsCpRaM8zzDk0SgjoHWdFTMApDS+uGzk11GIg5tU0wLQtJIttGybRgAIzO3QnRwKSbX2e8wzu579u3X79xUxW+nuwjkfXT7JT+50ACOOToEnQUG0bDsQOnLTbWAFQ84w9NBVT+fG6CTuxwHtNdFnlf2ZH3tgOnKRWJnORt7nzk13b3tF43nTN505wsuWfcD7iHd3d3dpTzP3Ot1yg9jHbKeUunQYlwAtEw-xLHnO8lD7kjpyf2xRcPBe3RE6eTwG5Ky2gyBoMnt36Mvvdv1gLtdAX974B1rtdaIe9x6TzQFnL43MxZeAgFXZyECSjRC7uPHuZBXLwKZkgmQKCwHby9r7IwL8IB01FtkGQE9yTIBJNkZgosNpENQaQuuPsY4WwDjgrolJaGSwqEAxhKsvisOQRwh+dcjDPxgVQrogpCDl0ISIYh58yFGD-tgleyjVFsPUdI8BI9QTXwUdQokORBHc30YgwxGi0GmKMNA3hnR+EV2seXOxkj2GLHVKpFYcJJBgDAPlKQLU0AACUIAnHUkiFEaIYmEAAKLqQxMrVW6tdpa2xoWagjBKAYlGAAH1GPNMYhBymqQrBpHmVCdJK0mkmQmWZxq5PsrNEyeJArOVCjkcKaUTKCFYFAWhEB2ShPCdIdAyTan3FGAAEgAGRjAJIsD6P1pTwDgHKQGmotRckpBkEAkhVbxCAA

**Comment by uguraslan** [comment]
@Moussa Thank you for providing a sample code with the playground app. We will be looking into it and will inform you when we have a solution for the issue.

**Comment by frank-weindel** [comment]
@Moussa We are going to give the developer the capability of inserting zero-width breaking spaces (Unicode: [0x200B](https://unicode-explorer.com/c/200B)) at any point they wish and the Lightning text renderers will use them as line breaking opportunities in addition to normal space characters. This will allow you to use the function you've defined in your example without having to insert artificial space characters which actually affect the display of the text when word wrapping does not occur.

We'll consider adding in more intrinsic support for non-Latin scripts in a plugin friendly way in the future, specifically with Lightning 3.0. But for now this feature should enable developers to implement deterministic word wrapping in a way that was not possible before.

**Comment by Moussa** [comment]
Thank you for the addition 👍.
