### ISSUE TITLE
Lightning interface to Selenium testing

### ISSUE THREAD

**Issue by milan-de** [rdkcentral/Lightning#462]
Hi guys,

is there any option of testing WebPages running "Lightning app" within HTML element "canvas" like this one:
https://sky.live.tv-apps.radioplayer.org/

by using Selenium testing framework? 
Does Lightning App release on one or another way access to all visible elements, so that one can use it to send key events like one get used by using Selenium framework?
Basically one have no idea how to detect if some "html element"/"lightning elements" like button selection are available at page or not in order to make some decision/navigation based on that.

Kind regards,
Milan

**Comment by frank-weindel** [comment]
Hi @milan-de, You should be able to utilize the Lightning Inspector to achieve what you are looking for. Take a look at: https://lightningjs.io/docs/#/tools/IntegrationTesting/index?id=integration-testing

**Comment by milan-de** [comment]
@frank-weindel so far I understand that would mean that inspector has to be enabled during application development, right ?
If one have no access to the application code and do testing as "black box" how would it be possible to access any element within canvas/lightningJS App? Any idea ?

**Comment by frank-weindel** [comment]
@milan-de If you are able to at least inject code onto a page that runs a Lightning app, you should be able to insert the Lightning Inspector yourself.

You'd want to include the JavaScript source of the inspector:
https://github.com/rdkcentral/Lightning/blob/master/devtools/lightning-inspect.js

And then copy it to call `attachInspector(window.lng)`

**Comment by imtiaz101325** [comment]
Hey @milan-de 
You should be able to add the code by running it in the [console](https://developer.chrome.com/docs/devtools/console/).

But the problem is that after the app has loaded calling `attachInspector` will do nothing.

Essentially, we have to do this before the app is launched and canvas is loaded.

You should find a clue [here](https://github.com/rdkcentral/Lightning-SDK/blob/401a9c0f136b7b4ae50038c37bf3f2733b0365b6/src/startApp.js#L50).

Good luck!

**Comment by milan-de** [comment]
Thanks @imtiaz101325 that is giving me enough clue how to start and I am greatfull for that. On other side this is going more into hacking and twisting it to any other use then originally meant then productive using it. Not even originaly purpose is clear to me. I must be too old but before it was not that important at file header to write copyrights but purpose and some basic setup/functional description of it. I guess it is not for me at this moment at least. Thanks @imtiaz101325, @frank-weindel anyway as I learn some new stuff already.
