### ISSUE TITLE
Class property this._tag

### ISSUE THREAD

**Issue by achille1789** [rdkcentral/Lightning#467]
Hi, I was building a Lightning component class in my app extending "Lightning.Component".
I found out that I cannot create a property this._tag otherwise the app crashes when I try to use the lightning ".tag()" API.
I think that this happen because in lightning/core Element.mjs there is "_tag" method.
Would be better use a double underscore for the internal lightning names?

My code:
`
_build() {
    this._tag = 'hello';
    this._myComponent = this.tag('MyComponent');
  }
`

Console error:
<img width="518" alt="Screenshot 2023-03-23 at 14 42 04" src="https://user-images.githubusercontent.com/20861796/227241603-0a95ebf2-1143-41c7-b3fd-ef2e1dc36290.png">

**Comment by imtiaz101325** [comment]
Hey @achille1789,
Lightning uses the underscore prefix internally but also to expose top level API. We normally try to avoid using that in our application code.
Do you think the value gained would justify the amount of work it would be to rename all of them? I'm just trying to understand if this has impacts other than nicer convention.

**Comment by achille1789** [comment]
Hi @imtiaz101325 thanks for getting back to me.
It is not a huge problem because yes, we can just avoid to use _tag and all works fine. I was just raising this, because the use of "internal" variable names starting with an underscore is a wide practice and people may face errors because of this (like the above) and maybe find difficult to get to the root of the error.
I am not also saying that you should rename all the variables of the core library but maybe you can take this in consideration for the next v3 version of Lightning.

I give you a brief overview of the impact of this for us.
In our company we are used to prepend "internal" names with an underscore. My team builds lightning components in shared libraries following the component name provided by the design teams.
They designed a new Tag component and we built it in lightning, but we had to call it TagComponent (breaking all the naming convention kept so far), because we know that the keeping the name Tag, the first time that other teams were going use it, they will write this `this._tag = this.tag('Tag')` and then raise a bug ticket because the component throws an error.

Again, it is not a huge a problem, it was just an observation.
Thanks

**Comment by uguraslan** [comment]
Hey @achille1789, thank you for bringing up your concerns regarding variable/method naming conventions in Lightning. We appreciate your insights and understand the impact this issue has on your team's development practices. Although adopting a different naming convention for "internal" variables could benefit the project, it may not be feasible to implement such changes in the Lightning 2.x versions, considering the potential backward compatibility issues and the amount of work involved.

Nevertheless, we assure you that your suggestion will be thoughtfully considered for the v3 version of Lightning.

I will be closing this issue as we are unable to address it further in the current 2.x versions. However, please don't hesitate to reopen the issue if you'd like to provide more feedback or share additional thoughts. Moreover, if you or your team can devise a solution that resolves this issue while maintaining backward compatibility, we would be more than happy to review a pull request.
