### ISSUE TITLE
Incomplete regression fix on ziggo platforms

### ISSUE THREAD

**Issue by Sv-Th** [rdkcentral/Lightning#475]
Regarding following pull: https://github.com/rdkcentral/Lightning/pull/364

A new generation of hardware was released with the following user agent:
````Mozilla/5.0 (Linux armv7l) AppleWebKit/602.1.28+ (KHTML, like Gecko) Version/9.1 Safari/601.5.17 HZN/4.46 (MN=2008C-STB-PROD;PC=EOS2STB;FV=EOS2008C-mon-web-00.05-157-ap-AL-20230209074548-na002;)````

This causes the earlier mentioned regression fix to not function for users with new generation of boxes.
This reintroduces the blocky/missing text issue of https://github.com/rdkcentral/Lightning/issues/363

The fix could be as simple as adding ``|| navigator.userAgent.indexOf('EOS2STB') !== -1`` to the isZiggo utils check. However, something to keep in mind is that if or when a new generation is introduced, the issue could resurface.

**Comment by wouterlucas** [comment]
I think its better if we take the whole User Agent detection thing out and make this a switchable setting people can configure. That way it's not bound to project specific devices and it's a generic setting people can turn on. Making it future proof for next iterations of the Ziggo HW.

**Comment by Sv-Th** [comment]
Apparently this generic setting has already been added (https://github.com/rdkcentral/Lightning/issues/363#issuecomment-1308359557). A similar issue has been created in the past as well. 

My mistake. I will be closing the issue and pull request in this case.
