### ISSUE TITLE
Pointer support - Event model

### ISSUE THREAD

**Issue by itsjamie** [rdkcentral/Lightning#485]
The event model for pointers doesn't follow the event flow setup that mimics the browser for handling key events.

The event model for the keyboard / remote controls maps well to the model of the browser, supporting both the capturing phase and the bubbling phase.

```
if (!this.stage.application.focusTopDownEvent(["_captureKey"], obj)) {
    this.stage.application.focusBottomUpEvent(["_handleKey"], obj);
}
```

The implementation for the click handling allows for much less control, supporting only finding the deepest element with a handler, and having no method of even opting-out of handling the click at a parent component. Requiring the user to fire an event or signal to have a parent element handle clicks.

Ideally, the same model would be applied to the pointer events, as is applied to the keyboard events, mapping to the browser style of the capturing and bubbling phases of event propagation.

```
if (clientX <= this.stage.w && clientY <= this.stage.h) {
    this.stage.application.fireBottomUpClickHandler(obj);
}
```

Meaning that the bottom most handler is the only one with the current model that ever has the chance to opt to handle the event.

```
fireBottomUpClickHandler(obj) {
    const {clientX, clientY} = obj;
    const target = this._getTargetChild(clientX, clientY);
    let child = target;

    // Search tree bottom up for a handler
    while (child !== null) {
        if (child && child["_handleClick"]) {
            child._handleClick(target);
            break;
        }
        child = child.parent;
    }
}
```

**Comment by erikhaandrikman** [comment]
there is a feature branch available with bubbling support: https://github.com/rdkcentral/Lightning/tree/feature/bubble-pointer-event 

Explicitly returning `false` in the event handler will make the event bubble up
