### ISSUE TITLE
Regression with rendering text that uses normal spaces

### ISSUE THREAD

**Issue by itsjamie** [rdkcentral/Lightning#488]
Having a text texture with extra non-breaking space characters in a text element that has wordWrapWidth enabled seems to have regressed with the implementation of the Zero Width Spaces for languages like Chinese.

If you take the string `reproduction `, and run it through the splitWords function, the space character is dropped from the returned match, leading to the space no longer being considered part of the rendering.

**Comment by itsjamie** [comment]
We used this feature to support rendering text that changed colors in the middle of strings.

So, if there is another better method for doing wordWrapWidth and allowing for `<span style="color: red">Red</span> Text`, then it doesn't matter.

But what we were looking to resolve was..

```Welcome to the NEW version of our application. The text is very long and will overflow, but we want certain text to be different colors to draw attention.```

So we would instead write:

```Welcome to the ___ version of our application. The text is very long and will overflow, but we want ____________ to be different colors to draw attention.```

Then we could render the small sections of text, calculate where they should go, and then place them in those empty spots.

This kept the overall word wrapping algorithm working and allowed for the alignment to be correct. With this, that strategy no longer works. But, if there was a better way to handle inline text colourization that wouldn't matter!

**Comment by frank-weindel** [comment]
Thanks @itsjamie for the report. Have you looked into the Advanced Text Renderer at all for what you're trying to do? https://lightningjs.io/api/lightning-core/interfaces/lightning.textures.texttexture.settings#advancedRenderer

**Comment by itsjamie** [comment]
That's exactly the kind of pointer I was hoping for we had missed. Thanks @frank-weindel. I'll get us to convert this particular section of code.

It has made us change to using padding in a few other places where prior we used whitespace.
