### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by philippe-wm** [rdkcentral/Lightning#490]
Currently Lightning core is published to npm as a monolithic JS distribution where everything is exported as one object, which doesn't allow tree-shaking of the unused functionality.

We currently optimise for canvas 2D compatible devices and by doing a custom build of Lightning removing the unused features we can reduce this dependency payload by 30% at least.

We appreciate that a simple pre-minified JS is good for many, but it would be nice to support tree-shaking without doing a custom Lightning build/fork.

**Comment by frank-weindel** [comment]
@philippe-wm Please give the linked PR branch a try and let me know if it works for you.

You should only need to build and pack the project and then install it as a file:
- `npm run build`
- `npm pack` should create  a file `lightningjs-core-2.10.0.tgz`
- Move the file to your project directory and run: `npm install file:lightningjs-core-2.10.0.tgz`

**Comment by elsassph** [comment]
@frank-weindel what branch are you referring too?
