### ISSUE TITLE
Alpha channel heuristic when not using ImageWorker doesn't deal with uppercase file extensions

### ISSUE THREAD

**Issue by pascalatfetch** [rdkcentral/Lightning#493]
I tried loading an externally supplied file with `.PNG` extension, and the alpha channel wasn't clear.
It seems that the heuristic is to just look at the file path, whereas the ImageWorker detects mime types.
That said, there is a flag `hasAlpha` which the ImageWorker subsequently ignores.

Should the non-worker based code path use a `FileReader` and do mime type detection as well, or is that too much of a performance hit? At the very least the heuristic string comparison should ignore case.

Looking into this, the code responsible here is this line:

https://github.com/rdkcentral/Lightning/blob/master/src/platforms/browser/WebPlatform.mjs#L270

![image](https://github.com/rdkcentral/Lightning/assets/123550560/4cb3d722-3d13-43f0-8613-49024d775d28)

**Comment by pascalatfetch** [comment]
@wouterlucas Great work.

Do you think the image worker ignoring the `hasAlpha` flag is a potential issue?

**Comment by wouterlucas** [comment]
During my tests it didn’t seem to ignore the hasAlpha flag on the function itself. 

This might be higher up the chain if that is the case, I can look into it but suggest we move this along for the next release.

**Comment by pascalatfetch** [comment]
I don't think it's super important. Just saw this as a discrepancy.
Maybe I didn't explain what I meant correctly:

When providing the `hasAlpha` flag to the actual component, it is overriding the heuristic outcome when not running in a worker, but ignored when the worker finishes.

Instead, on worker execution, the `hasAlphaChannel` result is the only value that is acknowledged.

![image](https://github.com/rdkcentral/Lightning/assets/123550560/fb749ca1-1be7-48fd-824c-a351446a31ff)

**Comment by wouterlucas** [comment]
ah yes, thanks for clarifying. It indeed seems to be ignored on the image worker because it relies on the mimeType:
https://github.com/rdkcentral/Lightning/blob/master/src/platforms/browser/ImageWorker.mjs#L306

Although I agree that doesn't make sense and it should probably be included when evaluating the alpha also on the image worker. I do think the mimeType itself is solid way to check for the alpha channel, not sure if having an override is necessary at this point.

**Comment by elsassph** [comment]
It is certainly awkward when image URLs don't include `.png` somewhere... so we add `#.png` to the URL in places where we know we want the image to be transparent...
