### ISSUE TITLE
Issue with dynamic width and height

### ISSUE THREAD

**Issue by DauMoe** [rdkcentral/Lightning#512]
Hi developer team and everyone,

I am developing some components but I got a few issues:

### Frirst
- I create rectangle with RoundedRectangle shader, but the height is a dynamic value, but for now the RoundedRectangle radius parameter must be a specific number. Can you make the radius units include "px" and percent? Cause I can't measure rectangle height
### Secondly
- Can **lng.Tools.getSvgTexture(url, w, h)** specify either the width or height only? In some cases, I only want to fix the height or width, while keeping the rest of the attributes values automatic and maintaining the aspect ratio
### Third
- I have component A nest component B and component A's width is dynamic (inherit parent because of using flexbox). How can I set component B width = x% * component A's width

**Comment by frank-weindel** [comment]
@DauMoe For your third question take a look at: https://lightningjs.io/docs/#/lightning-core-reference/RenderEngine/Elements/Positioning?id=dynamic-calculations

**Comment by wouterlucas** [comment]
The first and second feature idea's are great suggestions, but currently not available in the Lightning 2.x stack. As we've just released our Lightning 3.0 beta much of our focus is going towards that.

Unfortunately it's not feasible for us to add these to Lightning 2.x anymore, though we'd be more then happy to consider the suggestions for 3.0.

**Comment by DauMoe** [comment]
> @DauMoe For your third question take a look at: https://lightningjs.io/docs/#/lightning-core-reference/RenderEngine/Elements/Positioning?id=dynamic-calculations

Yeah thanks. I found this after raising the issue a few days 😂

**Comment by DauMoe** [comment]
> The first and second feature idea's are great suggestions, but currently not available in the Lightning 2.x stack. As we've just released our Lightning 3.0 beta much of our focus is going towards that.
> 
> Unfortunately it's not feasible for us to add these to Lightning 2.x anymore, though we'd be more then happy to consider the suggestions for 3.0.

Don't worry, I had found the solution for these issues. On the second one, I really hope LightningJs ver 3 can resolve it
