### ISSUE TITLE
Version 2.12.1 not including typescript types

### ISSUE THREAD

**Issue by adiffmike** [rdkcentral/Lightning#527]
https://github.com/rdkcentral/Lightning/blob/b25dcc13e13bc74a4a71caff19ce25253e5ffc66/scripts/src-to-dist.cjs#L17

This won't work as intended. path.extname() only returns the last extension so path.extname('Application.d.ts') returns ".ts"  It's not going to include typescript types.

https://nodejs.org/api/path.html#pathextnamepath

**Comment by marijnwebers** [comment]
@wouterlucas any idea when this fix gets released?

**Comment by wouterlucas** [comment]
just went out, let me know if that works for you @marijnwebers!

**Comment by marijnwebers** [comment]
Worked like a charm :), thanks all
